version: '3.7'
services:
  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: jeemongo

  app:
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
    restart: always
    depends_on:
      - mongo
    healthcheck:
      test: curl --fail http://localhost:8080/health/ready || exit 1
    build:
      context: .
      dockerfile: Dockerfile
#  app:
#    image: jee/mongo
#    volumes:
#      - ./target/jakarta-hello-world.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/ROOT.war
#    ports:
#      - "8080:8080"
#      - "4848:4848"
#      - "9009:9009"
#    restart: always
#    depends_on:
#      - mongo
#    healthcheck:
#      test: curl --fail http://localhost:8080/health/ready || exit 1
#    build:
#      context: .